uv_index, visibility, sun* added ref to #4
ErwinSteffens/darksky-influxdb pull request #5
Opened 2019-09-04 12:50 UTC by cagnulein

Here you are! :)

2019-09-10 14:53 UTC, cagnulein commented
@ErwinSteffens any news about this?

2019-09-10 18:23 UTC, ErwinSteffens requested changes
Sorry for the late reply. Thanks for the addition. 

A have a few small comments.

2019-09-10 18:23 UTC, ErwinSteffens commented on index.js
> +                sun_status = 1;
Nitpicking, but can you use the same formatting as in other places?

So camelCasing for the `sun_status` variables and braces on the correct places?

2019-09-10 18:23 UTC, ErwinSteffens commented on index.js
> +            if(moment().unix() > daily.sunriseTime && moment().unix() < daily.sunsetTime)
Can't you just use `(new Date()).getTime() / 1000` for getting epoch in seconds? I think pulling in moment.js as a dependency just for getting the epoch time is a bit of overkill.

2019-09-11 06:25 UTC, cagnulein commented
what do you think now?

2019-09-11 11:25 UTC, ErwinSteffens commented
LGTM.

@cagnulein  I assume you tested it?

2019-09-11 12:48 UTC, cagnulein commented
@ErwinSteffens yes OFC

2019-09-17 15:33 UTC, cagnulein commented
is it ok?

2019-09-17 15:43 UTC, ErwinSteffens commented
Yes, thnx

2019-09-17 15:43 UTC, merged